const easing = [
  { text: 'Custom', value: 'Custom' },
  { text: 'Linear', value: 'Linear' },
  { text: 'Stepped', value: 'Stepped' },
  { text: 'Quad.easeIn', value: 'Quad.easeIn' },
  { text: 'Cubic.easeIn', value: 'Cubic.easeIn' },
  { text: 'Quart.easeIn', value: 'Quart.easeIn' },
  { text: 'Quint.easeIn', value: 'Quint.easeIn' },
  { text: 'Sine.easeIn', value: 'Sine.easeIn' },
  { text: 'Expo.easeIn', value: 'Expo.easeIn' },
  { text: 'Circ.easeIn', value: 'Circ.easeIn' },
  { text: 'Elastic.easeIn', value: 'Elastic.easeIn' },
  { text: 'Back.easeIn', value: 'Back.easeIn' },
  { text: 'Bounce.easeIn', value: 'Bounce.easeIn' },
  { text: 'Quad.easeOut', value: 'Quad.easeOut' },
  { text: 'Cubic.easeOut', value: 'Cubic.easeOut' },
  { text: 'Quart.easeOut', value: 'Quart.easeOut' },
  { text: 'Quint.easeOut', value: 'Quint.easeOut' },
  { text: 'Sine.easeOut', value: 'Sine.easeOut' },
  { text: 'Expo.easeOut', value: 'Expo.easeOut' },
  { text: 'Circ.easeOut', value: 'Circ.easeOut' },
  { text: 'Elastic.easeOut', value: 'Elastic.easeOut' },
  { text: 'Back.easeOut', value: 'Back.easeOut' },
  { text: 'Bounce.easeOut', value: 'Bounce.easeOut' },
  { text: 'Quad.easeInOut', value: 'Quad.easeInOut' },
  { text: 'Cubic.easeInOut', value: 'Cubic.easeInOut' },
  { text: 'Quart.easeInOut', value: 'Quart.easeInOut' },
  { text: 'Quint.easeInOut', value: 'Quint.easeInOut' },
  { text: 'Sine.easeInOut', value: 'Sine.easeInOut' },
  { text: 'Expo.easeInOut', value: 'Expo.easeInOut' },
  { text: 'Circ.easeInOut', value: 'Circ.easeInOut' },
  { text: 'Elastic.easeInOut', value: 'Elastic.easeInOut' },
  { text: 'Back.easeInOut', value: 'Back.easeInOut' },
  { text: 'Bounce.easeInOut', value: 'Bounce.easeInOut' }
];

export default easing;