const emitterConfig = {
  active: true,
  visible: true,
  collideBottom: true,
  collideLeft: true,
  collideRight: true,
  collideTop: true,
  on: true,
  particleBringToTop: true,
  radial: true,
  frame: 'hexagon',
  frequency: 0,
  gravityX: 0,
  gravityY: 0,
  maxParticles: 0,
  timeScale: 1,
  blendMode: 0,
  accelerationX: [0],
  accelerationY: [0],
  alpha: [1],
  angle: { min: 0, max: 360, ease: 'Linear' },
  bounce: [0],
  delay: [0],
  lifespan: [1000],
  maxVelocityX: [10000],
  maxVelocityY: [10000],
  moveToX: [0],
  moveToY: [0],
  quantity: [1],
  rotate: [0],
  scale: [1],
  speed: [0],
  x: [400],
  y: [300],
  bounds: undefined,
  tint: [0xffffff],
  emitZone: undefined,
  deathZone: undefined,
};

export default emitterConfig;
